### ISSUE TITLE
Keestand Displaying Empty Page in Chrome

### ISSUE THREAD

**Issue by scaryghost** [evilrobot69/code#26]
Logged in to Keestand today on Chrome (v62.0.3202.75) and all I get is the add/save/options button, no data.  Exporting data yields an empty file.

The web console displays this stack trace:
```
old_sjcl.js:37 Uncaught invalid {message: "json decode: this isn't json!", toString: ƒ}
decode @ old_sjcl.js:37
decrypt @ old_sjcl.js:34
decrypt @ keestand.js:28
login_successful @ keestand.js:158
handleSuccess @ jquery.min.js:142
w.onreadystatechange @ jquery.min.js:141
XMLHttpRequest.send (async)
(anonymous) @ VM97:1
ajax @ jquery.min.js:141
salt_success @ keestand.js:117
handleSuccess @ jquery.min.js:142
w.onreadystatechange @ jquery.min.js:141
XMLHttpRequest.send (async)
(anonymous) @ VM97:1
ajax @ jquery.min.js:141
(anonymous) @ keestand.js:238
handle @ jquery.min.js:63
o @ jquery.min.js:56
```

The page loads fine on Brave (v0.19.53), Chromium (v59.0.3071.109 openSUSE build), and Firefox (v56.0).

**Comment by evilrobot69** [comment]
Try going to chrome://appcache-config and clearing anything to do with
Keestand

**Comment by scaryghost** [comment]
Went to ``chrome://appcache-internals/``, removed ``https://keestand.appspot.com/cache.manifest``, then restarted chrome, but still no luck.

**Comment by evilrobot69** [comment]
Huh, weird I'm running Chrome 62.0.3202.62 on Linux (Ubuntu-ish) with no
issue. What platform are you on? And what's your login username?

Thanks,

Ari

**Comment by scaryghost** [comment]
Ah interesting...Chrome v62.0.3202.75 on Win10 for me.  The other browsers I tried, listed in my OP, are on Win10, openSUSE, and openSUSE respectively, and those work just fine.

I'll email the username.
